// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const createApp = `-- name: CreateApp :one
INSERT INTO app (id) VALUES ( ? ) RETURNING id
`

func (q *Queries) CreateApp(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, createApp, id)
	err := row.Scan(&id)
	return id, err
}

const getApp = `-- name: GetApp :one
select id from app
where id = ?
`

func (q *Queries) GetApp(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	err := row.Scan(&id)
	return id, err
}
