// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type App struct {
	ID int64
}

type Record struct {
	ID        int64
	Version   int64
	Path      string
	Method    string
	Reqbody   string
	Resbody   string
	CreatedAt sql.NullTime
}

type Version struct {
	ID   int64
	Name string
	App  int64
}
